version: '3.9'

services:

  mysql:
    image: mysql:8.0
    container_name: agenda-mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agenda_db
      MYSQL_USER: agenda_user
      MYSQL_PASSWORD: 1234

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - agenda-network

  app:
    image: eclipse-temurin:21-jdk
    container_name: agenda-java
    working_dir: /app
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    depends_on:
      - mysql
    networks:
      - agenda-network

volumes:
  mysql_data:

networks:
  agenda-network: